# Segmentation configuration
segment:
  # Root dir for the output
  output_dir: /some/dir

  # Name of the output folder. Will be created in the 'output_dir'
  name: output_name

  # SAM model used for segmentation. Will be downloaded if needed.
  model: models/sam2.1_b.pt

  # Saving intermediate results (crops). Slows down the process
  save_intermediate_images: False

  # Saving final results (image with contours & image with labels)
  save_final_images: True

  # Images to segment. Can be folders with images or single images.
  datasets: 
    - /images/this_image.jpg
    - /images/another_image.png
    - /images/subfolder/a_folder_with_a_lot_of_images
